-- SQL Data Export
-- Project: Sincay Laravel
-- Note: This file is maintained for report/checklist submission.
-- Source data is generated by seeders in /database/seeders.

-- To regenerate real data dump:
-- 1) php artisan migrate:fresh --seed
-- 2) Use your DB tool to export "data only"
--    and replace this file content.

-- Seeders available:
-- RoleSeeder
-- UserSeeder
-- CategorySeeder
-- ProductSeeder
-- CouponSeeder

